version: '2'
services:
    jhenftest-app:
        image: jhenftest
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jhenftest-postgresql:5432/jhEnfTest
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=jhenftest-elasticsearch:9300
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES=zookeeper
        ports:
            - 8080:8080
    jhenftest-postgresql:
        extends:
            file: postgresql.yml
            service: jhenftest-postgresql
    jhenftest-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: jhenftest-elasticsearch
    kafka:
        extends:
            file: kafka.yml
            service: kafka
        environment:
            - KAFKA_ADVERTISED_HOST_NAME=kafka
    zookeeper:
        extends:
            file: kafka.yml
            service: zookeeper
